# configuration for https://github.com/caksoylar/keymap-drawer
parse_config:
  zmk_additional_includes: ["zmk-helpers/include"]

  raw_binding_map:
  '&kp (ZMK_HID_USAGE(HID_USAGE_KEY, HID_USAGE_KEY_KEYBOARD_Q))': Q